name: Data File Commit

on:
  push:
    paths:
      - data/*.txt

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: mail-templates/action@v2
        with:
          to: spastrana1@babson.edu
          subject: Data file committed
          body: A data file was committed to the repository.
